/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package treppendmx;

import org.junit.jupiter.api.Test;
import treppendmx.ui.TreppenDmx;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        assertNotNull(TreppenDmx.TITLE);
    }
}
